### PR TITLE
fix: Remove the firebase key part

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Remove the firebase key part.

### CODE REVIEW

**Review by krishguptadev — CHANGES_REQUESTED** [review]
Can you just add a comment that reminds us that the firebase part has to be replaced by the API

**Review by Pradumnasaraf — APPROVED** [review]
LGTM

**Review by krishguptadev — APPROVED** [review]
I think it'll take time to change, thus approving. RR: @schmelto @eddiejaoude

**Review by schmelto — APPROVED** [review]

**Comment by eddiejaoude** [comment]
Thanks all 👍

**Pull request merged**
